### ISSUE TITLE
Blog image animation

### ISSUE THREAD

**Issue by bradreeder** [Kata-Martagon/Kata-Martagon-Blog#26]
When I resize the screen to mobile size, and then I resize it to browser size the animation stops working and it just displays the last image as a default.

**Comment by g-sam** [comment]
For some reason I can't seem to replicate this issue. But on a related point, if you resize to just above the point the extra image column is added then you get a white space below the image. I guess they need to be higher to fill the space.

**Comment by MarckK** [comment]
Fixed.  There images on the left now smoothly resizes to viewport size.
