### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by otajor** [Kata-Martagon/Kata-Martagon-Blog#29]
It's quite unusual to have a bespoke menu html page. Normally the menu is a part of all pages, which allows quicker navigation from one page to another without going via the menu page.

**Comment by nogainbar** [comment]
Thats a great point! we discussed it between us and although we had different ideas and opinions, we made a decision to go with that (because noga was keen to try it out!) so I guess it was more of a stylistic decision rather then a 'functional' one.

**Comment by otajor** [comment]
You could have had a div with the same styling that is hidden until you click the menu icon - functionality AND styling! :P (you would have to include the div on all your pages)
